FROM python:3.8

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install watchdog[watchmedo]

# Copy the entrypoint script
COPY docker-entrypoint.dev.sh /docker-entrypoint.dev.sh
RUN chmod +x /docker-entrypoint.dev.sh

# Copy project
COPY . .

ENTRYPOINT ["/docker-entrypoint.dev.sh"]