# Generated by Django 3.2.19 on 2025-04-12 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_type', '0001_initial'),
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberLimitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.JSONField(help_text='Numbers to limit')),
                ('max_total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('draw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='number_limits', to='draw.draw')),
                ('game_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='number_limits', to='game_type.gametype')),
            ],
            options={
                'verbose_name': 'Number Limit Rule',
                'verbose_name_plural': 'Number Limit Rules',
                'ordering': ['-created_at'],
            },
        ),
    ]
