# Generated by Django 3.2.19 on 2025-04-12 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        ('draw', '0001_initial'),
        ('winning_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='owner_structure',
            field=models.ForeignKey(limit_choices_to={'node_type': 'bank'}, on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='structure.structure'),
        ),
        migrations.AddField(
            model_name='draw',
            name='winning_numbers',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draw', to='winning_record.winningrecord'),
        ),
    ]
