# Generated by Django 3.2.19 on 2025-04-12 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('bank', 'Bank'), ('branch', 'Branch'), ('other', 'Other')], default='branch', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=0)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='structure.structure')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='tenants.client')),
            ],
            options={
                'ordering': ['path'],
                'unique_together': {('name', 'parent', 'tenant')},
            },
        ),
    ]
